---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light, tag: '0.8.0'  }

inputs:
  - name: cf-networking-release-ci
  - name: cf-networking

run:
  path: cf-networking-release-ci/ci/tasks/check-empty-networking-opsfile
