---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: version
  - name: cf-networking-ci
  - name: cf-networking-master

run:
  path: cf-networking-ci/ci/tasks/shipit
