---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

inputs:
  - name: variables
    optional: true
  - name: cf-networking-release-ci
  - name: cf-networking-release-assets

params:
  ENVIRONMENT_TAG: ~
  CF_USERNAME: ~
  CF_PASSWORD: ~
  SLI_ORG: ~
  SLI_SPACE: ~
  SLI_APP_NAME: ~
  SLI_APP_PATH: cf-networking-release-ci/src/example-apps/proxy/
  MAP_ROUTES: false

run:
  path: cf-networking-release-ci/ci/tasks/sli-setup
