---
image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/deploy
    tag: 0.4.0

platform: linux

inputs:
  - name: cf-deployment-concourse-tasks
  - name: cf-networking-dev
  - name: cf-networking-release-ci
  - name: env-repo

run:
  path: cf-networking-release-ci/ci/tasks/upload-acceptance-test-release

params:
  BBL_STATE_DIR:
